name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.1"

      - name: Build application
        run: ./scripts/buildprod.sh

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker to use gcloud as a credential helper
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build and push Docker image using Docker directly
        run: |
          # Build the Docker image locally
          docker build -t us-central1-docker.pkg.dev/notely-476113/notely-ar-repo/notely:latest .

          # Push to Artifact Registry
          docker push us-central1-docker.pkg.dev/notely-476113/notely-ar-repo/notely:latest
